version: '3'
services:
  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    container_name: tabix
    ports: 
       - 8120:80
    volumes:
      - tabix:/
    networks:
      - net
  ch-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    privileged: true
    volumes:
      - clickhouse_conf:/etc/clickhouse-server/
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
      - 9001:9000
    networks:
      - net
volumes:
  clickhouse_data:
    driver: local
  clickhouse_conf:
    driver: local
  tabix:
    driver: local
 
networks:
  net:
    external: false
