version: '3'
services:
  ch-client:
    image: yandex/clickhouse-client
    command: ['--host', 'server']
  ch-server:
    image: yandex/clickhouse-server
    privileged: true
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
volumes:
  chserver:
    driver: local
  chclient:
    driver: local