version: '3'
services:
  ch-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    privileged: true
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
      - 9001:9000
volumes:
  chserver:
    driver: local

networks:
  net-clickhouse:
    external: false