version: '3'
services:
  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    contailer_name: tabix
    ports: 
       - 8120:80
    volumes:
      - tabix:/
  ch-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    privileged: true
    volumes:
      - chserver:/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
      - 9001:9000
    networks:
      netoverlay:
        ipv4_address: 172.19.1.3
volumes:
  chserver:
    driver: local
  tabix:
    driver: local
 
networks:
  netoverlay:
    driver: overlay
    ipam:
      config:
        - subnet: 172.19.1.0/24
