version: "3"

networks:
  default:
    driver: bridge
    
services:
  namenode:
    image: bde2020/hadoop-namenode
    container_name: namenode
    ports:
      - 9870:9870
      - 9000:9000
    environment:
      - CLUSTER_NAME=Qbit
    env_file:
      - ./env.env

  datanode:
    image: bde2020/hadoop-datanode
    container_name: datanode
    depends_on:
      - namenode
    ports:
      - 9864:9864
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    links:
      - "namenode:namenode"
    env_file:
      - ./env.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager
    container_name: resourcemanager
    ports:
      - 8088:8088
    links:
      - "namenode:namenode"
      - "datanode:datanode"
    depends_on:
      - namenode
      - datanode
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    env_file:
      - ./env.env

  nodemanager:
    image: bde2020/hadoop-nodemanager
    container_name: nodemanager
    links:
      - "namenode:namenode"
      - "datanode:datanode"
      - "resourcemanager:resourcemanager"
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./env.env

  historyserver:
    image: bde2020/hadoop-historyserver
    container_name: historyserver
    links:
      - "namenode:namenode"
      - "datanode:datanode"
      - "resourcemanager:resourcemanager"
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./env.env

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    env_file:
      - ./env.env
    links:
      - "hive-metastore:hive-metastore"
      - "hive-metastore-postgresql:hive-metastore-postgresql"
    depends_on:
      - hive-metastore
      - hive-metastore-postgresql
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./env.env
    command: /opt/hive/bin/hive --service metastore
    links:
      - "namenode:namenode"
      - "datanode:datanode"
      - "hive-metastore-postgresql:hive-metastore-postgresql"
    depends_on:
      - namenode
      - datanode
      - hive-metastore-postgresql
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    ports:
      - "5432:5432"


  # presto:
  #   image: shawnzhu/prestodb:0.181
  #   container_name: presto
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - net

volumes:
  namenode:
    driver: local
  datanode:
    driver: local
  historyserver:
    driver: local
  hbase_data:
    driver: local

networks:
  net:
    external: false