version: '3'
services:
  hbase:
    image: harisekhon/hbase:1.3
    container_name: hbase
    ports:
      - "16010:16010"
    volumes:
      - hbasedata:/hbase
    networks:
      - net-hbase
volumes:
  hbasedata:
    driver: local
    
networks:
  net-hbase:
    external: false
