version: '3'
services:
  hbase:
    image: harisekhon/hbase:1.3
    container_name: hbase
    ports:
      - "16010:16010"
      - "2181:2181"
    volumes:
      - hbase_data:/hbase
    networks:
      - net
volumes:
  hbase_data:
    driver: local
    
networks:
  net:
    external: false
