version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    restart: always
    container_name: mysql
    privileged: true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - net-mysql
volumes:
  mysqldata:
    driver: local
networks:
  net-mysql:
    external: false