version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    restart: always
    container_name: mysql
    privileged: true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - net-mysql
    networks:
      extnetwork:
        ipv4_address: 172.19.0.2
volumes:
  mysqldata:
    driver: local
networks:
  netoverlay:
    driver: overlay