version: '3'
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    ports:
     - "8848:8848"
     - "9100:9100"
    networks:
      - net

volumes:
  nacos_data:
    driver: local
    
networks:
  net:
    external: false