version: '3'
services:
  nexus:
    image: 'sonatype/nexus3'
    restart: always
    privileged: true
    container_name: nexus
    ports:
      - 8000:8000
      - 8081:8081
    volumes:
      - nexusdata:/nexus-data
    networks:
      - net-nexus
volumes:
  nexusdata:
    driver: local

networks:
  net-nexus:
    external: false