version: '3'
services:
  rabbitmq:
    image: 'rabbitmq'
    restart: always
    privileged: true
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - net-mq
volumes:
  rabbitmqdata:
    driver: local

networks:
  net-mq:
    external: false