version: '3'
services:
  redis:
    image: 'redis'
    restart: always
    container_name: redis
    privileged: true
    ports:
      - 6379:6379
    command: 
      redis-server /etc/redis/redis.conf --appendonly yes
    volumes:
      - redis_data:/data
      - redis_conf:/etc/redis
    networks:
      - net
      
volumes:
  redis_data:
    driver: local
  redis_conf:
    driver: local

networks:
  net:
    external: false