version: '3'
services:
  redis:
    image: 'redis'
    restart: always
    container_name: redis
    privileged: true
    ports:
      - 6379:6379
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - "${REDIS_DIR}/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "${REDIS_DIR}/data:/data"
    networks:
      - net-redis
networks:
  net-redis:
    external: false