version: "3"
services:
  seata-server:
    container_name: seata-server
    image: seataio/seata-server
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
    networks:
      - net
      
networks:
  net:
    external: false