version: "3"
services:
  spark-master:
    image: singularities/spark
    command: start-spark master
    container_name: spark-master
    hostname: master
    ports:
      - "6066:6066"
      - "7070:7070"
      - "8080:8080"
      - "50070:50070"
  spark-worker:
    image: singularities/spark
    container_name: spark-worker
    command: start-spark worker master
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    links:
      - spark-master