version: '3'
services:
  zookeeper:
    image: 'zookeeper:3.6.2'
    restart: always
    privileged: true
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - net

volumes:
  zk_data:
    driver: local

networks:
  net:
    external: false