version: "3"

services:
  centos01:
    image: guozhenhua/centos:1.3
    container_name: centos01
    privileged: true
    networks:
      net1:
        ipv4_address: 172.18.0.21
    ports:
      - '8080:80'
    extra_hosts:
      - "centos01:172.18.0.21"
      - "centos02:172.18.0.22"
      - "centos03:172.18.0.23"
    tty: true

  centos02:
    image: guozhenhua/centos:1.3
    container_name: centos02
    privileged: true
    networks:
      net1:
        ipv4_address: 172.18.0.22
    ports:
      - '8081:80'
    extra_hosts:
      - "centos01:172.18.0.21"
      - "centos02:172.18.0.22"
      - "centos03:172.18.0.23"
    tty: true

  centos03:
    image: guozhenhua/centos:1.3
    container_name: centos03 
    privileged: true
    networks:
      net1:
        ipv4_address: 172.18.0.23
    ports:
      - '8082:80'
    extra_hosts:
      - "centos01:172.18.0.21"
      - "centos02:172.18.0.22"
      - "centos03:172.18.0.23"
    tty: true

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
  
volumes:
  centos01:
    driver: local
  centos02:
    driver: local
  centos03:
    driver: local
