version: "3.3"
services:
 rabbitmq1:
    image: 'rabbitmq'
    hostname: rabbitmq1
    restart: always
    privileged: true
    container_name: rabbitmq1
    networks:
      net1:
        ipv4_address: 172.30.0.2
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
    volumes:
      - rabbitmq1:/var/lib/rabbitmq
 rabbitmq2:
    image: 'rabbitmq'
    restart: always
    privileged: true
    hostname: rabbitmq2
    container_name: rabbitmq2
    networks:
      net1:
        ipv4_address: 172.30.0.3
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq1
    volumes:
      - rabbitmq2:/var/lib/rabbitmq
    links:
      - rabbitmq1
    # extra_hosts:多机环境下替换links即可
    #   - "rabbit1:10.5.0.3"
volumes:
  rabbitmq:
    driver: local
  rabbitmq2:
    driver: local
networks:
  net1:
     driver: bridge # 创建一个docker 的桥接网络
     ipam:
       driver: default
       config:
          -
           subnet: 172.30.0.0/16