version: "3.3"
services:
  zk1:
    image: zookeeper:3.4
    restart: always
    container_name: zk1
    ports:
      - "2181:2181"
    volumes:
      - zk1/data:/data
      - zk1/datalog:/datalog
      - zk1/conf:/conf
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
  zk2:
    image: zookeeper:3.4
    restart: always
    container_name: zk2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    volumes:
      - zk2/data:/data
      - zk2/datalog:/datalog
      - zk2/conf:/conf
 
  zk3:
    image: zookeeper:3.4
    restart: always
    container_name: zk3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    volumes:
      - zk3/data:/data
      - zk3/datalog:/datalog
      - zk3/conf:/conf
volumes:
  zk1:
    driver: local
  zk2:
    driver: local
  zk3:
    driver: local

networks:
  zk-master:
     driver: bridge # 创建一个docker 的桥接网络
     ipam:
       driver: default
       config:
          -
           subnet: 172.50.0.0/16
  zk-slave:
       driver: bridge
       ipam:
         driver: default
         config:
            -
             subnet: 172.30.0.0/16