require('keymaps')
require('settings')
require('autocmd')
require('plugins')
require('plugins.themes')
require('plugins.nvim_tree')
require('plugins.db')
require('plugins.fterm')
require('plugins.telescope')
require('plugins.closetag')
-- require('plugins.nvim_treesitter')
-- require('plugins.cmp')
