require('settings')
require('keymaps')
require('autocmd')
require('plugins')

require('plugins.themes')
require('plugins.nvim_tree')
require('plugins.db')
require('plugins.fterm')
require('plugins.telescope')
require('plugins.closetag')

require('lsp.cmp')
require('lsp.mason')
require('lsp.nvim_treesitter')
