version: "3"

services:
  spark01:
    image: guozhenhua/spark:1.0
    container_name: spark01
    privileged: true
    networks:
      net1:
        ipv4_address: 172.18.0.11
    ports:
      - 8080:8080
      - 7070:7070
    extra_hosts:
      - "centos01:172.18.0.11"
      - "centos02:172.18.0.12"
      - "centos03:172.18.0.13"
    tty: true

  spark02:
    image: guozhenhua/spark:1.0
    container_name: spark02
    privileged: true
    networks:
      net1:
        ipv4_address: 172.18.0.12
    extra_hosts:
      - "centos01:172.18.0.11"
      - "centos02:172.18.0.12"
      - "centos03:172.18.0.13"
    tty: true

  spark03:
    image: guozhenhua/spark:1.0
    container_name: spark03 
    privileged: true
    networks:
      net1:
        ipv4_address: 172.18.0.13
    extra_hosts:
      - "centos01:172.18.0.11"
      - "centos02:172.18.0.12"
      - "centos03:172.18.0.13"
    tty: true

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
  
volumes:
  centos01:
    driver: local
  centos02:
    driver: local
  centos03:
    driver: local