version: '3'
services:
  kibana:
    image: kibana:6.8.10
    ports:
      - "5601:5601"
    volumes:
      - "${KIBANA_DIR}/config/kibana.yml:/usr/share/kibana/config/kibana.yml"
networks:
  net-kibana:
    external: false