version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: es
    privileged: true
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES_DATA_PATH}:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT}:9200"
      - "${ES_PORT2}:9300"
    networks:
      net:
        ipv4_address: ${ES_IP}

  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    privileged: true
    ports:
      - "${CEREBRO_PORT}:9000"
    command:
      - -Dhosts.0.host=http://${ES_IP}:9200
    networks:
      net:
        ipv4_address: ${CEREBRO_IP}

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    container_name: kibana
    privileged: true
    ports:
      - "5601:5601"
    environment:
      - elasticsearch.hosts=http://${ES_IP}:9200
      - server.name=kibana
      - server.host=0
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    networks:
      net:
        ipv4_address: ${KIBANA_IP}

networks:
   net:
      ipam:
         config:
         - subnet: ${SUB_NET}
           gateway: ${GATEWAY_IP}
