version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    restart: always
    container_name: mysql
    privileged: true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:${MYSQL_PORT}'
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_CONFIG_PATH}:/etc/mysql/conf.d
    networks:
      net:
        ipv4_address: ${MYSQL_IP}

networks:
   net:
      ipam:
         config:
         - subnet: ${SUB_NET}
           gateway: ${GATEWAY_IP}
