version: '3'
services:
  redis:
    image: 'redis'
    restart: always
    container_name: redis
    privileged: true
    ports:
      - 6379:${REDIS_PORT}
    command: 
      redis-server --appendonly yes
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONFIG_PATH}:/etc/redis
    networks:
      net:
        ipv4_address: ${REDIS_IP}

networks:
   net:
      ipam:
         config:
         - subnet: ${SUB_NET}
           gateway: ${GATEWAY_IP}
