version: '3'
services:
  redis:
    image: 'redis/redis-stack-server:latest'
    restart: always
    container_name: redis-stack-server
    privileged: true
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data
      # - ${REDIS_CONFIG_PATH}:/redis-stack.conf
    networks:
      net:
        ipv4_address: ${REDIS_IP}

networks:
   net:
      ipam:
         config:
         - subnet: ${SUB_NET}
           gateway: ${GATEWAY_IP}
