version: '3'
services:

  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    container_name: tabix
    privileged: true
    ports: 
       - ${TABIX_PORT}:80
    networks:
      net:
        ipv4_address: ${TABIX_IP}

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    privileged: true
    volumes:
      - ${CLICK_HOSE_DATA_PATH}:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - ${CLICK_HOSE_PORT2}:8123
      - ${CLICK_HOSE_PORT}:9000
    networks:
      net:
        ipv4_address: ${CLICK_HOSE_IP}

networks:
   net:
      ipam:
         config:
         - subnet: ${SUB_NET}
           gateway: ${GATEWAY_IP}
