version: '3'
services:
  zookeeper:
    image: 'zookeeper:3.6.2'
    restart: always
    privileged: true
    container_name: zookeeper
    ports:
      - ${ZK_PORT}:2181
    volumes:
      - ${ZK_DATA_PATH}:/data
      - ${ZK_CONF_PATH}:/conf/zoo.cfg
    networks:
      net:
        ipv4_address: ${ZK_IP}

networks:
   net:
      ipam:
         config:
         - subnet: ${SUB_NET}
           gateway: ${GATEWAY_IP}
