version: '3'
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    restart: always
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    ports:
     - "${NACOS_IP}:8848"
     - "${NACOS_IP2}:9100"
    networks:
      net:
        ipv4_address: ${NACOS_IP}

networks:
   net:
      ipam:
         config:
         - subnet: ${SUB_NET}
           gateway: ${GATEWAY_IP}
