version: '3'
services:
  nextcloud:
    image: nextcloud 
    container_name: nextcloud
    restart: always
    privileged: true
    ports:
      - '${NEXTCLOUD_PORT}:80'
    volumes:
      - "${NEXT_CLOUD_DIR}:/var/www/html"
    environment:
      MYSQL_HOST: ${MYSQL_IP}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      VIRTUAL_HOST: ${NEXT_CLOUD_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${NEXT_CLOUD_LETSENCRYPT_HOST}
    networks:
      net:
        ipv4_address: ${NEXT_CLOUD_IP}

networks:
   net:
      ipam:
         config:
         - subnet: ${SUB_NET}
           gateway: ${GATEWAY_IP}
