version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: es
    privileged: true
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES_DATA_PATH}:/usr/share/elasticsearch/data
      # - ${ES_CONFIG_PATH}:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "${ES_PORT}:9200"
      - "${ES_PORT2}:9300"
    networks:
      net:
        ipv4_address: ${ES_IP}

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    container_name: kibana
    privileged: true
    ports:
      - "5601:5601"
    environment:
      - elasticsearch.hosts=http://${ES_IP}:9200
      - server.name=kibana
      - server.host=0
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    volumes:
      - ${KIBANA_CONFIG_PATH}:/usr/share/kibana/config/kibana.yml
    networks:
      net:
        ipv4_address: ${KIBANA_IP}

networks:
   net:
      ipam:
         config:
         - subnet: ${SUB_NET}
           gateway: ${GATEWAY_IP}
