version: '3'
services:
  hbase:
    image: harisekhon/hbase:1.3
    container_name: hbase
    ports:
      - "${HBASE_PORT}:16010"
      #- "2181:2181"
    volumes:
      - ${HBASE_DATA_PATH}:/hbase-data
    networks:
      net:
        ipv4_address: ${HBASE_IP}

networks:
   net:
      ipam:
         config:
         - subnet: ${SUB_NET}
           gateway: ${GATEWAY_IP}
