version: '3'
services:
  nextcloud:
    image: nextcloud 
    container_name: nextcloud
    restart: always
    ports:
      - '8000:80'
    volumes:
      - "${NEXT_CLOUD_PORT}/nextcloud:/var/www/html"
    environment:
      MYSQL_HOST: ${NEXT_CLOUD_MYSQL_HOST}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      VIRTUAL_HOST: ${NEXT_CLOUD_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${NEXT_CLOUD_LETSENCRYPT_HOST}
  
