version: '3'
services:
  nexus:
    image: 'sonatype/nexus3'
    restart: always
    privileged: true
    container_name: nexus
    ports:
      - 8000:8000
      - 8081:8081
    volumes:
      - nexus_data:/nexus-data
    networks:
      - net
volumes:
  nexus_data:
    driver: local

networks:
  net:
    external: false