version: '3'
services:
  rabbitmq:
    image: 'rabbitmq'
    restart: always
    privileged: true
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - net
volumes:
  rabbitmq_data:
    driver: local

networks:
  net:
    external: false