version: "3"
services:

  spark-master:
    image: singularities/spark
    command: start-spark master
    container_name: spark-master
    hostname: master
    ports:
      - "${SPARK_PORT}:6066"
      - "${SPARK_PORT2}:7070"
      - "${SPARK_PORT3}:8080"
      - "${SPARK_PORT4}:50070"
    networks:
      net:
        ipv4_address: ${SPARK_MASTER_IP}

  spark-worker:
    image: singularities/spark
    container_name: spark-worker
    command: start-spark worker master
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    links:
      - spark-master
    networks:
      net:
        ipv4_address: ${SPARK_WORKER_IP}

networks:
   net:
      ipam:
         config:
         - subnet: ${SUB_NET}
           gateway: ${GATEWAY_IP}
