version: '3'
services:
  zookeeper:
    image: 'zookeeper:3.6.2'
    restart: always
    privileged: true
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - ${ZK_DATA_PATH}:/data
    networks:
      - net

networks:
  net:
    external: false