version: '3'
services:
  zookeeper:
    image: 'zookeeper:3.6.2'
    restart: always
    privileged: true
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - ${ZK_DATA_PATH}:/data
    networks:
      net:
        ipv4_address: 172.19.0.4
networks:
   net:
      ipam:
         config:
         - subnet: 172.19.0.0/16
           gateway: 172.19.0.1


