version: "3.3"
services:
 mysql-master:
    image: 'mysql:5.7'
    restart: always
    container_name: mysql-master
    privileged: true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3339:3306'
    volumes:
      - "mysqlMaster/data:/var/lib/mysql"
      - "mysqlMaster/conf:/etc/mysql/conf.d"
 mysql-slave:
    image: 'mysql:5.7'
    restart: always
    container_name: mysql-slave
    privileged: true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${SLAVE_ROOT_PASSWORD}
    ports:
      - '3340:3306'
    volumes:
      - "mysqlSlave/data:/var/lib/mysql"
      - "mysqlSlave/conf:/etc/mysql/conf.d"
volumes:
  mysqlMaster:
    driver: local
  mysqlSlave:
    driver: local